name: Generate RSS Feed

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run feed generator
        run: node generateRSS.js

      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add feeds/mergedFeed.json seenKeywords.json
          git commit -m "Update merged feed"
          git push
